version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-  # fallback to using the latest cache if no exact match is found

    - run:
        name: install dependences
        command: yarn install --frozen-lockfile

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: check build for errors
        command: npm run build

    - run:
        name: check code style
        command: npm run lint